# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@1.2

commands:
  setup_dependencies:
    description: "Install depenencies"
    parameters:
      after-deps:
        description: "Install dependencies"
        type: steps
        default: []
    steps:
      - run: 
          name: "Install open JDK"
          command: sudo add-apt-repository -y ppa:openjdk-r/ppa
      - run:
          name: "Install setuptools"
          command: pip install -U pip setuptools
      - run:
          name: "Install tox"
          command: pip install -U tox==3.13.0
      - run:
          name: "Run Tox"
          command: "tox --notest -e style"
      - run: 
          name: "Install qq"
          command: sudo apt-get -qq update
      - run: 
          name: "No install recommends for JDK"
          command: sudo apt-get install -y openjdk-8-jdk --no-install-recommends
      - run: 
          name: "Run Java Alternatives install for JDK"
          command: sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
      - run:
          name: "Run pip install setup tools"
          command: pip install -U pip setuptools
      - run:  
          name: "Install Tox"
          command: pip install -U tox==3.13.0
      - run:  
          name: "Get Tox Envs"
          command: python scripts/get_tox_envs.py --plan $ALL_ENVS
      - steps: << parameters.after-deps >>

# We want to make sure we run this only on master branch, release, or when we make tags
run_complex: &run_complex
  filters:
    branches:
      only:
        - master
        - /release-v.*/
    tags:
      only: /.*/

jobs:

  Python36-Unit-Tests: 
    docker:
      - image: cimg/python:3.6
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ALL_ENVS: --all
      toxinidir: ~/
      working_directory: ~/

    steps:
      - checkout
      - setup_dependencies
      - run:
          name: "Make log files"
          command: mkdir -p ~/visual_relation/log && touch ~/visual_relation/log/visual_relation-1.log; mkdir -p ~/recsys/log && touch ~/recsys/log/recsys-1.log; mkdir -p ~/getting_started/log && touch ~/getting_started/log/getting_started-1.log; mkdir -p ~/spam/log && touch ~/spam/log/spam-1.log; mkdir -p ~/crowdsourcing/log && touch ~/crowdsourcing/log/crowdsourcing-1.log; mkdir -p ~/multitask/log && touch ~/multitask/log/multitask-1.log; mkdir -p ~/drybell/log && touch drybell/log/drybell-1.log;

      - run:
          name: "Run Tox"
          command:  tox -e $(python scripts/get_tox_envs.py $ALL_ENVS)

  

workflows:
  version: 2

  Unit-Tests:
    jobs:
      - Python36-Unit-Tests
    
